# Generated by Django 3.0.5 on 2020-04-03 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('discription', models.TextField()),
                ('cr_date', models.DateTimeField(auto_now_add=True)),
                ('crimg', models.ImageField(null=True, upload_to='images\\')),
            ],
        ),
    ]
